Feature Request: Allows logging of errors that raised in adapter or other middleware
lostisland/faraday pull request #1460
Opened 2022-11-10 23:32 UTC by epaew

## Description
This patch introduces logging of errors that raised in adapter or other (deeper) middlewares.

I am very much looking forward to merged this patch. Thanks.
## Todos
List any remaining work that needs to be done, i.e:
- [x] Tests
- [x] Documentation

## Additional Notes
Optional section

2022-11-11 10:52 UTC, iMacTia requested changes
@epaew this looks really good 👏 !
I particularly like the idea of having an `on_error` hook available to all middleware as the base for this implementation.
The code looks great and is well test-covered.

The only thing I'd ask is to add one more piece to the docs ([in this section](https://github.com/lostisland/faraday/pull/1460/files#diff-15d532e8f1e05dec44aa4498ffe3094821c9b0f7f32d06161b0608e327175780R42)) to illustrate how the configuration block now accepts also a `error` option 👍

2022-11-11 14:01 UTC, iMacTia commented
Ah sorry, the link is not working as expected (probably because the line is outside of the changed code).
I'm referring to this section:

```
### Include and exclude headers/bodies
By default, the `logger` middleware logs only headers for security reasons, however, you can configure it
to log bodies as well, or disable headers logging if you need to. To do so, simply provide a configuration hash
when you add the middleware to the stack:

conn = Faraday.new(url: 'http://httpbingo.org') do |faraday|
  faraday.response :logger, nil, { headers: true, bodies: true }
end

Please note this only works with the default formatter.
```

which should be updated to mention that errors will also be logged if you pass `true`.
You also make a good point that we should probably illustrate the following syntax as well:

```ruby
faraday.response :logger, nil, { headers: { error: true }, bodies: { error: false } }
```

but to be fair, we're not doing that for the current available options, so I won't consider this a blocker for this PR

2022-11-11 21:45 UTC, epaew commented
I added commits. 👍

2022-11-14 15:56 UTC, iMacTia approved these changes

2022-11-14 16:31 UTC, merged